spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: config0
server:
  port: 8888

---

spring:
  profiles: config1
server:
  port: 8889