spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 6  #配置在服务提供端, 失效时间 6s内没有发renew就认为该服务失效
    lease-renewal-interval-in-seconds: 2 #配置在服务提供端，renew的频率 这里是2s发一次
---

spring:
  profiles: config0
server:
  port: 8888

---

spring:
  profiles: config1
server:
  port: 8889