spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/