---
spring:
  profiles: peer1
  application:
    name: peer1
eureka:
  instance:
    hostname: peer1
    lease-expiration-duration-in-seconds: 6  #配置在服务提供端, 失效时间 6s内没有发renew就认为该服务失效
    lease-renewal-interval-in-seconds: 2 #配置在服务提供端，renew的频率 这里是2s发一次
  client:
    serviceUrl:
      defaultZone: http://peer2:9002/eureka/
  server:
    eviction-interval-timer-in-ms: 10000  #配置在euraka-server端失效时间 10s扫描一次有没有失效服务，检测标准就是超过配置在服务端的失效时间没有renew的服务
server:
  port: 9001
---
spring:
  profiles: peer2
  application:
    name: peer2
eureka:
  instance:
    hostname: peer2
    lease-expiration-duration-in-seconds: 6  #配置在服务提供端, 失效时间 6s内没有发renew就认为该服务失效
    lease-renewal-interval-in-seconds: 2 #配置在服务提供端，renew的频率 这里是2s发一次
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/
  server:
    eviction-interval-timer-in-ms: 10000  #配置在euraka-server端失效时间 10s扫描一次有没有失效服务，检测标准就是超过配置在服务端的失效时间没有renew的服务
server:
  port: 9002