spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
#  instance:
#    hostname: localhost
#    lease-expiration-duration-in-seconds: 6
#    lease-renewal-interval-in-seconds: 2
  client:
    register-with-eureka: false
#    fetch-registry: false