#eureka 配置
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 6  #配置在服务提供端, 失效时间 6s内没有发renew就认为该服务失效
    lease-renewal-interval-in-seconds: 2 #配置在服务提供端，renew的频率 这里是2s发一次
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true  #是否从euraka上拉取服务 默认true
    registry-fetch-interval-seconds: 3 #30s从euraka上拉取一次服务列表 默认30s

spring:
  application:
    name: web
  cloud:
    config:
      profile: dev,cloud
#      uri: http://localhost:8888   这是不整合eureka，直接url获取
      discovery:    #用eureka来发现config服务
        enabled: true
        service-id: config
server:
  port: 8080

#actuator 配置
endpoints:
  actuator:
    enabled: true
  env:
    enabled: true
    sensitive: true
  beans:
    enabled: true
management:
  security:
    enabled: false
