#eureka 配置
eureka:
  instance:
    hostname: web
    metadata-map:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/
    fetch-registry: true  #是否从euraka上拉取服务 默认true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30 #30s从eureka上更新一次注册表

spring:
  application:
    name: web
##   加载规则config-server端，1.application.yml中指定profile; 2.{application.name】-{profile}-{label}.yml(这里是web-dev.yml)中指定profile
#  cloud:
#    config:
#      profile: dev
##      uri: http://localhost:8888   这是不整合eureka，直接url获取
#
#      discovery:    #用eureka来发现config服务
#        enabled: true
#        service-id: config
#  datasource:
#    url: jdbc:mysql://localhost:3306/somethingnew?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#  data:
#    mongodb:
#      uri: mongodb://cqx:cqx@47.92.6.210:27017/pikachu
  mvc:
    view:
        prefix:
        suffix: .html
  thymeleaf:
    cache: false

#github:
#  oauth2:
#    client:
#      id: f875735a0ca1cc8b0da2
#      secret: 3f08b906ffb0350105721be1152f7c9a16a93626
#      redirectUri: http://localhost:8080

server:
  port: 10000

logging:
  level:
    root: debug
#actuator 配置
management:
  endpoints:
    enabled-by-default: true
  server:
    port: 11000

name: cqx